name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_ROCK_04CD9FB0F }}
          app_location: "/"      # your index.html is at the repo root
          output_location: ""    # no build output folder
          skip_app_build: true
          skip_api_build: true
