name: Azure Static Web Apps CI/CD
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          # Use the secret you will add in step C below
          azure_static_web_apps_api_token: ${{ AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"     # index.html is at repository root
          output_location: ""   # no build folder
          skip_app_build: true
          skip_api_build: true
