name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Azure/static-web-apps-deploy@v1
        with:
          # 👇 this must match the secret name you already have
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_ROCK_04CD9FB0F }}

          # Your site lives in /OneCalendar (where index.html is)
          app_location: /OneCalendar

          # We’re not building anything—serve files as-is
          output_location: /
          skip_app_build: true

          # No backend yet
          skip_api_build: true
